### ISSUE TITLE
Error install newbot-cli on Ubuntu 18^*

### ISSUE THREAD

**Issue by ildevelop** [newbotjs/newbot-cli#1]
try:
`sudo npm install -g newbot-cli ` 

- ngrok - error storing binary to local file [Error: EACCES: permission denied, open

- UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open   gactions CLI

`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngrok@3.2.7 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ngrok@3.2.7 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2019-12-21T15_22_16_081Z-debug.log
`

**Comment by RSamaium** [comment]
Hello,

The problem surely lives with a global installation

Try a local installation

```
npm install newbot-cli
npx newbot new <your-project>
```

**Additional information**

https://github.com/newbotjs/newbot-framework/issues/1
